# Server Configuration
server.port=8083
spring.application.name=order-management-service



# Resilience4j - Circuit Breaker Configuration
resilience4j.circuitbreaker.instances.customerServiceCB.register-health-indicator=true
resilience4j.circuitbreaker.instances.customerServiceCB.sliding-window-size=6
resilience4j.circuitbreaker.instances.customerServiceCB.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.customerServiceCB.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.customerServiceCB.permitted-number-of-calls-in-half-open-state=3

# Actuator (Opcional, para monitorear el estado del circuito)
management.endpoints.web.exposure.include=health,info,circuitbreakers

# Services URLs (System APIs)
services.customer.url:http://localhost:8081/customers
services.order.url:http://localhost:8082/orders