# Server Configuration
server.port=8084
spring.application.name=order-management-service

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v1/api-docs


# --- Configuración para el Circuit Breaker de External Services ---
resilience4j.circuitbreaker.instances.externalServicesCB.registerHealthIndicator=true
resilience4j.timelimiter.instances.externalServicesCB.timeout-duration=3s
resilience4j.circuitbreaker.instances.externalServicesCB.slidingWindowSize=8
resilience4j.circuitbreaker.instances.externalServicesCB.failureRateThreshold=50
resilience4j.circuitbreaker.instances.externalServicesCB.minimumNumberOfCalls=4
resilience4j.circuitbreaker.instances.externalServicesCB.ignore-exceptions=\
  org.springframework.web.client.HttpClientErrorException.NotFound,\
  org.springframework.web.client.HttpClientErrorException.BadRequest,\
  com.nova.order.management.service.exception.exceptions.ResourceNotFoundException,\
  com.nova.order.management.service.exception.exceptions.BadRequestException,\
  org.springframework.web.bind.MethodArgumentNotValidException


# Actuator (Opcional, para monitorear el estado del circuito)
management.endpoints.web.exposure.include=health,info,circuitbreakers

# Services URLs (System APIs)
services.customer.url=http://localhost:8082/customers
services.order.url=http://localhost:8083/orders